name: padaria_cjm2
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.5
  flutter_secure_storage: ^10.0.0
  firebase_auth: ^6.3.0
  firebase_core: ^4.6.0
  provider: ^6.0.5
  cloud_firestore: ^6.2.0
  intl: ^0.20.2
  timezone: ^0.9.0
  shimmer: ^3.0.0
  dropdown_button2: ^3.0.0
  flutter_bloc: ^9.1.1
  flutter_native_splash: ^2.4.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter:

  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/

  fonts:
    # 🔹 Poppins (principal)
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf      # 400
        - asset: assets/fonts/Poppins-SemiBold.ttf     # 600
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf         # 700
          weight: 700

    # 🔹 Montserrat (secundária elegante)
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf   # 400
        - asset: assets/fonts/Montserrat-Medium.ttf    # 500
          weight: 500
        - asset: assets/fonts/Montserrat-SemiBold.ttf  # 600
          weight: 600

    # 🔹 Oswald (títulos impactantes)
    - family: Oswald
      fonts:
        - asset: assets/fonts/Oswald-Regular.ttf       # 400
        - asset: assets/fonts/Oswald-Bold.ttf          # 700
          weight: 700

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#E0E7ED"
  image: assets/images/logo.png
  android: true
  ios: true
  web: false
  fullscreen: true

  android_12:
    image: assets/images/logo.png
    color: "#E0E7ED"
